### ISSUE TITLE
Staffeln often loses connectivity to MySQL server randomly

### ISSUE THREAD

**Issue by mnaser** [vexxhost/staffeln#126]
In an Atmosphere environment, we're seeing times where it loses connectivity to the database server causing the readiness checks to fail:

```
2024-01-18 10:07:43.355 1 ERROR sqlalchemy.pool.impl.QueuePool [-] Exception during reset or similar: pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')
2024-01-18 10:07:43.355 1 ERROR sqlalchemy.pool.impl.QueuePool Traceback (most recent call last):
2024-01-18 10:07:43.355 1 ERROR sqlalchemy.pool.impl.QueuePool   File "/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 988, in _finalize_fairy
2024-01-18 10:07:43.355 1 ERROR sqlalchemy.pool.impl.QueuePool     fairy._reset(
2024-01-18 10:07:43.355 1 ERROR sqlalchemy.pool.impl.QueuePool   File "/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1436, in _reset
2024-01-18 10:07:43.355 1 ERROR sqlalchemy.pool.impl.QueuePool     pool._dialect.do_rollback(self)
2024-01-18 10:07:43.355 1 ERROR sqlalchemy.pool.impl.QueuePool   File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 691, in do_rollback
2024-01-18 10:07:43.355 1 ERROR sqlalchemy.pool.impl.QueuePool     dbapi_connection.rollback()
2024-01-18 10:07:43.355 1 ERROR sqlalchemy.pool.impl.QueuePool   File "/venv/lib/python3.10/site-packages/pymysql/connections.py", line 488, in rollback
2024-01-18 10:07:43.355 1 ERROR sqlalchemy.pool.impl.QueuePool     self._read_ok_packet()
2024-01-18 10:07:43.355 1 ERROR sqlalchemy.pool.impl.QueuePool   File "/venv/lib/python3.10/site-packages/pymysql/connections.py", line 448, in _read_ok_packet
2024-01-18 10:07:43.355 1 ERROR sqlalchemy.pool.impl.QueuePool     pkt = self._read_packet()
2024-01-18 10:07:43.355 1 ERROR sqlalchemy.pool.impl.QueuePool   File "/venv/lib/python3.10/site-packages/pymysql/connections.py", line 739, in _read_packet
2024-01-18 10:07:43.355 1 ERROR sqlalchemy.pool.impl.QueuePool     packet_header = self._read_bytes(4)
2024-01-18 10:07:43.355 1 ERROR sqlalchemy.pool.impl.QueuePool   File "/venv/lib/python3.10/site-packages/pymysql/connections.py", line 795, in _read_bytes
2024-01-18 10:07:43.355 1 ERROR sqlalchemy.pool.impl.QueuePool     raise err.OperationalError(
2024-01-18 10:07:43.355 1 ERROR sqlalchemy.pool.impl.QueuePool pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')
2024-01-18 10:07:43.355 1 ERROR sqlalchemy.pool.impl.QueuePool
```

**Comment by ricolin** [comment]
I'm working on two things:

- [ ] To add timeout time in config from Atmosphere so we can have more tolerance buffer
- [ ] To add retry for get api calls in staffeln when facing `pymysql.err.OperationalError`
